### ISSUE TITLE
drag area randomly appears on youtube

### ISSUE THREAD

**Issue by ucarrasco** [raindropio/extensions#19]
![image](https://cloud.githubusercontent.com/assets/2777461/22974288/ede74708-f381-11e6-9204-be882124ca05.png)

I'm pretty sure I didn't start dragging any link, and this appears after a few minutes when I use youtube, it would only go out if I start dragging a link then stop.

Before I understand it's a bug, I thought it was normal behaviour and that the extension was getting intrusive, other users may think the same.

**Comment by exentrich** [comment]
Thanks! Now fixed!
